# Sets up a pgAdmin4 container with persistent storage and connects to a PostgreSQL database.
# Defines a Docker service for pgAdmin4, exposing it on port 15432 and connecting to a PostgreSQL database with credentials from environment variables.
version: '3.8'

services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json      
      - pgadmin_data:/var/lib/pgadmin:rw      
    ports:
      - 15432:15432
    env_file: ".env"
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      # Default user for desktop mode (SERVER_MODE = False)
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      # Default password for desktop mode (SERVER_MODE = False)
      PGADMIN_DEFAULT_PASSWORD: password      
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 15432    
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo '${DATABASE_HOST}:5432:*:${DATABASE_USER}:${DATABASE_PASSWORD}' > /tmp/pgpassfile && /entrypoint.sh"


volumes:
  pgadmin_data:
    
  
