apiVersion: v1
kind: Service
metadata:
  labels:
    app: amplifi
  name: redis
  namespace: amplifi-dev
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    app: redis
