name: Check if alembic migrations updated

on:
  pull_request:
    paths: ["backend/app/alembic/**"]
    branches:
      - dev
      - master

  workflow_dispatch:

jobs:
  check-migration-needed:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: PR comment with reactions
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ## Hello Developer! :wave:
            #### ATTENTION:
            Your changes require alembic migration scripts to be re-run. Please remember to run `alembic upgrade` once after deployment is completed.
            **Command:** `kubectl exec pod/<POD_ID> --namespace amplifi-dev -- alembic upgrade head`
          reactions: eyes
          comment-tag: alembic-check
