/* This code snippet is a JavaScript file that defines a React component called `RootLayout`. Here is a
breakdown of what the code is doing: */
import localFont from "next/font/local";
import "./globals.css";
import CommonClient from "./CommonClient";
import CommonDataWrapper from "./CommonDataWrapper";
import { PostHogProvider } from "./posthogprovider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Amplifi",
  description: "Generated by create next app",
};

// const ttHoves = localFont({
//   src: [
//     {
//       path: "./fonts/TT Hoves Pro Trial Regular.ttf",
//       weight: "300",
//       style: "regular",
//     },
//     {
//       path: "./fonts/TT Hoves Pro Trial Medium.ttf",
//       weight: "400",
//       style: "medium",
//     },
//     {
//       path: "./fonts/TT Hoves Pro Trial DemiBold Italic.ttf",
//       weight: "500",
//       style: "Demibold",
//     },
//     {
//       path: "./fonts/TT Hoves Pro Trial Bold.ttf",
//       weight: "700",
//       style: "bold",
//     },
//   ],
//   variable: "--font-tt-hoves",
// });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} ${ttHoves.variable} antialiased`}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PostHogProvider>
          <CommonDataWrapper>{children}</CommonDataWrapper>
        </PostHogProvider>
        <CommonClient />
      </body>
    </html>
  );
}
