---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-amplifi-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thoughtswinsystems/amplifi.git
    targetRevision: k8s-deployment-release
    path: k8s/ongc/azure
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: amplifi-dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.29.0
    chart: vault
    helm:
      valuesObject:
        ui:
          enabled: true
#        server:
#          postStart:
#            - "/bin/sh"
#            - "-c"
#            - "vault operator unseal Z5YIIb8ogILZi9DDP5TbQQjOq+lnbSNBen/3i6WvWa8="
  destination:
    server: https://kubernetes.default.svc
    namespace: amplifi-vault

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
