"""empty message

Revision ID: c7b1365a8daa
Revises: 40cd2caa28ab
Create Date: 2024-11-05 04:50:52.039616

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'c7b1365a8daa'
down_revision = '40cd2caa28ab'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinations', sa.Column('destination_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('destinations', 'destination_type')
    # ### end Alembic commands ###
