"""empty message

Revision ID: afad8004cf75
Revises: 9dca50b4fd5d
Create Date: 2024-10-21 18:48:17.022473

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'afad8004cf75'
down_revision = '9dca50b4fd5d'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinations', sa.Column('pg_vector', sa.JSON(), nullable=False))
    op.add_column('schedule_config', sa.Column('cron_expression', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('schedule_config', 'hour')
    op.drop_column('schedule_config', 'month_of_year')
    op.drop_column('schedule_config', 'day_of_month')
    op.drop_column('schedule_config', 'minute')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_config', sa.Column('minute', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('schedule_config', sa.Column('day_of_month', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('schedule_config', sa.Column('month_of_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('schedule_config', sa.Column('hour', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('schedule_config', 'cron_expression')
    op.drop_column('destinations', 'pg_vector')
    # ### end Alembic commands ###
