"""empty message

Revision ID: 601d456fc201
Revises: e32e17f94e3f
Create Date: 2024-12-12 05:28:57.488955

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '601d456fc201'
down_revision = 'e32e17f94e3f'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_file_links', sa.Column('r2r_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset_file_links', 'r2r_id')
    # ### end Alembic commands ###
