"""empty message

Revision ID: e3e0640094ff
Revises: f4cfe0396006
Create Date: 2024-11-19 06:27:20.721170

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'e3e0640094ff'
down_revision = 'f4cfe0396006'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_info',
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_documentation_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('technical_documentation_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('version'),
    sa.UniqueConstraint('version')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deployment_info')
    # ### end Alembic commands ###
