"""empty message

Revision ID: dfc5b065a7de
Revises: 04c0e1ee8927
Create Date: 2024-10-23 19:17:50.278546

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dfc5b065a7de'
down_revision = '04c0e1ee8927'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination_databricks',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('destination_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('workspace_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cluster_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('database_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destination_databricks_id'), 'destination_databricks', ['id'], unique=False)
    op.create_table('destination_pgvector',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('destination_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('host', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destination_pgvector_id'), 'destination_pgvector', ['id'], unique=False)
    op.drop_column('destinations', 'pg_vector')
    op.alter_column('embedding_config', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('embedding_config', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('destinations', sa.Column('pg_vector', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_destination_pgvector_id'), table_name='destination_pgvector')
    op.drop_table('destination_pgvector')
    op.drop_index(op.f('ix_destination_databricks_id'), table_name='destination_databricks')
    op.drop_table('destination_databricks')
    # ### end Alembic commands ###
