"""empty message

Revision ID: e32e17f94e3f
Revises: dc9988dbf090
Create Date: 2024-12-05 09:05:27.777569

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'e32e17f94e3f'
down_revision = 'dc9988dbf090'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('status', sa.String(), nullable=True))
    op.add_column('files', sa.Column('source_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'source_id')
    op.drop_column('files', 'status')
    # ### end Alembic commands ###
