"""empty message

Revision ID: 783e6c3310fe
Revises: 6ad43882c662
Create Date: 2024-12-17 08:23:38.477067

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '783e6c3310fe'
down_revision = '6ad43882c662'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('azure_fabric',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('source_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('container_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sas_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id', 'source_id')
    )
    op.create_index(op.f('ix_azure_fabric_id'), 'azure_fabric', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_azure_fabric_id'), table_name='azure_fabric')
    op.drop_table('azure_fabric')
    # ### end Alembic commands ###
