"""empty message

Revision ID: dc9988dbf090
Revises: 4faace2404b8
Create Date: 2024-11-27 05:35:20.419101

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'dc9988dbf090'
down_revision = '4faace2404b8'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_ingestion', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'r2r_provider_chunking_config', ['chunking_config_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'r2r_provider_chunking_config', type_='unique')
    op.alter_column('file_ingestion', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
