"""empty message

Revision ID: 6ad43882c662
Revises: 6a4ce9d49bfe
Create Date: 2024-12-14 00:02:58.772027

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '6ad43882c662'
down_revision = '6a4ce9d49bfe'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_histories', sa.Column('context_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_histories', 'context_ids')
    # ### end Alembic commands ###
