"""empty message

Revision ID: 04c0e1ee8927
Revises: afad8004cf75
Create Date: 2024-10-15 09:22:31.966676

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '04c0e1ee8927'
down_revision = 'afad8004cf75'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_config',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('dataset_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rerank_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_dimension', sa.Integer(), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.Column('add_title_as_prefix', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_config_id'), 'embedding_config', ['id'], unique=False)
    op.create_index(op.f('ix_embedding_config_name'), 'embedding_config', ['name'], unique=False)
    op.create_unique_constraint(None, 'default_provider_chunking_config', ['chunking_config_id'])
    op.create_unique_constraint(None, 'unstructured_provider_chunking_config', ['chunking_config_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unstructured_provider_chunking_config', type_='unique')
    op.drop_constraint(None, 'default_provider_chunking_config', type_='unique')
    op.drop_index(op.f('ix_embedding_config_name'), table_name='embedding_config')
    op.drop_index(op.f('ix_embedding_config_id'), table_name='embedding_config')
    op.drop_table('embedding_config')
    # ### end Alembic commands ###
