"""Add 'dataset_required' column to 'tools' table

Revision ID: e0e3bd08cc57
Revises: a554bb28baae
Create Date: 2025-07-16 04:20:21.159630

This migration adds a new column 'dataset_required' to the 'tools' table.
The column is initially nullable, backfilled with a default value of False,
and then altered to be non-nullable. This ensures that all existing and
future rows have a value for this column.
"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0e3bd08cc57'
down_revision = 'a554bb28baae'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add the column as nullable
    op.add_column('tools', sa.Column('dataset_required', sa.Boolean(), nullable=True))
    
    # Step 2: Backfill existing rows with default value (False)
    op.execute("UPDATE tools SET dataset_required = false WHERE dataset_required IS NULL")
    
    # Step 3: Alter the column to be NOT NULL
    op.alter_column('tools', 'dataset_required', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'dataset_required')
    # ### end Alembic commands ###
