"""empty message

Revision ID: 3bfb31e6514e
Revises: 292c9ae74ae9
Create Date: 2025-03-17 07:45:55.020877

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '3bfb31e6514e'
down_revision = '292c9ae74ae9'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destination_databricks', sa.Column('warehouse_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('destination_databricks', 'cluster_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destination_databricks', sa.Column('cluster_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('destination_databricks', 'warehouse_id')
    # ### end Alembic commands ###
