"""empty message

Revision ID: b2352476eb92
Revises: 6218212f0a26
Create Date: 2025-06-03 09:57:02.173152

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'b2352476eb92'
down_revision = '6218212f0a26'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatapps', sa.Column('agent_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key('chatapps_agent_id_fkey', 'chatapps', 'agents', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chatapps_agent_id_fkey', 'chatapps', type_='foreignkey')
    op.drop_column('chatapps', 'agent_id')
    # ### end Alembic commands ###
