"""empty message

Revision ID: 2239985c531a
Revises: caa90aa04629
Create Date: 2025-04-05 07:06:34.452864

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '2239985c531a'
down_revision = 'ec7ec955a781'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###

    # written manually
    op.execute("ALTER TYPE fileingestionstatustype ADD VALUE 'Splitting'")
    op.execute("ALTER TYPE fileingestionstatustype RENAME TO fileingestionstatustype_old")
    op.execute("CREATE TYPE fileingestionstatustype AS ENUM ('Processing', 'Failed', 'Success', 'Not_Started', 'Exception', 'Splitting')")
    op.execute("""ALTER TABLE file_ingestion 
                 ALTER COLUMN status TYPE fileingestionstatustype 
                 USING status::text::fileingestionstatustype""")
    op.execute("DROP TYPE fileingestionstatustype_old")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # written manually
    op.execute("ALTER TYPE fileingestionstatustype RENAME TO fileingestionstatustype_old")
    op.execute("CREATE TYPE fileingestionstatustype AS ENUM ('Processing', 'Failed', 'Success', 'Not_Started')")
    op.execute("""ALTER TABLE file_ingestion
                 ALTER COLUMN status TYPE fileingestionstatustype 
                 USING status::text::fileingestionstatustype""")
    op.execute("DROP TYPE fileingestionstatustype_old")
    # ### end Alembic commands ###

