"""empty message

Revision ID: 4958fd8b64d0
Revises: 4383afef26bb
Create Date: 2025-07-26 13:21:39.493297

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '4958fd8b64d0'
down_revision = '2e267cc09832'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_dataset_file_link_composite', 'dataset_file_links', ['dataset_id', 'file_id'], unique=False)
    op.create_index('idx_dataset_file_link_dataset_id', 'dataset_file_links', ['dataset_id'], unique=False)
    op.create_index('idx_dataset_file_link_file_id', 'dataset_file_links', ['file_id'], unique=False)
    op.create_index('idx_dataset_name', 'datasets', ['name'], unique=False)
    op.create_index('idx_dataset_name_workspace', 'datasets', ['name', 'workspace_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_dataset_workspace_active', 'datasets', ['workspace_id', 'deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_document_dataset_id', 'documents', ['dataset_id'], unique=False)
    op.create_index('idx_document_file_dataset', 'documents', ['file_id', 'dataset_id', 'deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_document_file_id', 'documents', ['file_id'], unique=False)
    op.create_index('idx_document_processing_status', 'documents', ['processing_status'], unique=False)
    op.create_index('idx_file_filename', 'files', ['filename'], unique=False)
    op.create_index('idx_file_filename_lower', 'files', ['filename'], unique=False, postgresql_using='btree', postgresql_ops={'filename': 'text_pattern_ops'})
    op.create_index('idx_file_filename_trgm', 'files', ['filename'], unique=False, postgresql_using='gin', postgresql_ops={'filename': 'gin_trgm_ops'})
    op.create_index('idx_file_workspace_id', 'files', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_file_workspace_id', table_name='files')
    op.drop_index('idx_file_filename_trgm', table_name='files', postgresql_using='gin', postgresql_ops={'filename': 'gin_trgm_ops'})
    op.drop_index('idx_file_filename_lower', table_name='files', postgresql_using='btree', postgresql_ops={'filename': 'text_pattern_ops'})
    op.drop_index('idx_file_filename', table_name='files')
    op.drop_index('idx_document_processing_status', table_name='documents')
    op.drop_index('idx_document_file_id', table_name='documents')
    op.drop_index('idx_document_file_dataset', table_name='documents', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_document_dataset_id', table_name='documents')
    op.drop_index('idx_dataset_workspace_active', table_name='datasets', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_dataset_name_workspace', table_name='datasets', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_dataset_name', table_name='datasets')
    op.drop_index('idx_dataset_file_link_file_id', table_name='dataset_file_links')
    op.drop_index('idx_dataset_file_link_dataset_id', table_name='dataset_file_links')
    op.drop_index('idx_dataset_file_link_composite', table_name='dataset_file_links')
    # ### end Alembic commands ###
