"""empty message

Revision ID: 5bbfe1a3d59f
Revises: 2e7236ad593b
Create Date: 2025-01-16 00:34:06.495481

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel  # added


# revision identifiers, used by Alembic.
revision = "5bbfe1a3d59f"
down_revision = "2e7236ad593b"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # Manually written
    op.execute(
        """
        UPDATE chat_app_generation_configs
        SET llm_model = 'GPT35'
        WHERE llm_model = 'GPT3.5'
    """
    )
    op.execute(
        """
        CREATE TYPE chatmodelenum AS ENUM('GPT35', 'GPT4o');
    """
    )
    op.execute(
        """
        ALTER TABLE chat_app_generation_configs 
        ALTER COLUMN llm_model TYPE chatmodelenum 
        USING llm_model::text::chatmodelenum;
    """
    )
    # ### end Alembic commands ###


def downgrade():
    # Note downgrade doesn't change it back, shouldn't be issue since backend doesn't support 3.5 anymore
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chat_app_generation_configs",
        "llm_model",
        existing_type=sa.Enum("GPT35", "GPT4o", name="chatmodelenum"),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
