"""empty message

Revision ID: f508fb884e52
Revises: 0fe2a9a9339a
Create Date: 2025-03-21 07:27:30.857402

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'f508fb884e52'
down_revision = '0fe2a9a9339a'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_extraction_status',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('dataset_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('collection_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extraction_started_at', sa.DateTime(), nullable=False),
    sa.Column('extraction_completed_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_extraction_status_collection_id'), 'graph_extraction_status', ['collection_id'], unique=False)
    op.create_index(op.f('ix_graph_extraction_status_dataset_id'), 'graph_extraction_status', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_graph_extraction_status_document_id'), 'graph_extraction_status', ['document_id'], unique=False)
    op.create_index(op.f('ix_graph_extraction_status_id'), 'graph_extraction_status', ['id'], unique=False)
    op.add_column('datasets', sa.Column('graph_build_phase', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('datasets', sa.Column('graph_build_requested_at', sa.DateTime(), nullable=True))
    op.add_column('datasets', sa.Column('graph_build_completed_at', sa.DateTime(), nullable=True))
    op.add_column('datasets', sa.Column('last_extraction_check_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'last_extraction_check_at')
    op.drop_column('datasets', 'graph_build_completed_at')
    op.drop_column('datasets', 'graph_build_requested_at')
    op.drop_column('datasets', 'graph_build_phase')
    op.drop_index(op.f('ix_graph_extraction_status_id'), table_name='graph_extraction_status')
    op.drop_index(op.f('ix_graph_extraction_status_document_id'), table_name='graph_extraction_status')
    op.drop_index(op.f('ix_graph_extraction_status_dataset_id'), table_name='graph_extraction_status')
    op.drop_index(op.f('ix_graph_extraction_status_collection_id'), table_name='graph_extraction_status')
    op.drop_table('graph_extraction_status')
    # ### end Alembic commands ###
