"""empty message

Revision ID: 4b10d3d5dcc8
Revises: 5bbfe1a3d59f
Create Date: 2025-01-21 06:26:05.000625

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '4b10d3d5dcc8'
down_revision = '5bbfe1a3d59f'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_ingestion', sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_ingestion', 'task_id')
    # ### end Alembic commands ###
