"""empty message

Revision ID: 433dceb5e9e5
Revises: 292c9ae74ae9
Create Date: 2025-03-14 19:34:27.164766

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '433dceb5e9e5'
down_revision = '292c9ae74ae9'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_histories', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_histories', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_histories', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_sessions', sa.Column('total_tokens_per_chat_session', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('chat_sessions', sa.Column('input_tokens_per_chat_session', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('chat_sessions', sa.Column('output_tokens_per_chat_session', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('chatapps', sa.Column('total_tokens_per_chat_app', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('chatapps', sa.Column('input_tokens_per_chat_app', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('chatapps', sa.Column('output_tokens_per_chat_app', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatapps', 'output_tokens_per_chat_app')
    op.drop_column('chatapps', 'input_tokens_per_chat_app')
    op.drop_column('chatapps', 'total_tokens_per_chat_app')
    op.drop_column('chat_sessions', 'output_tokens_per_chat_session')
    op.drop_column('chat_sessions', 'input_tokens_per_chat_session')
    op.drop_column('chat_sessions', 'total_tokens_per_chat_session')
    op.drop_column('chat_histories', 'total_tokens')
    op.drop_column('chat_histories', 'output_tokens')
    op.drop_column('chat_histories', 'input_tokens')
    # ### end Alembic commands ###
