"""empty message

Revision ID: 8f3df49b6e4f
Revises: 31e468a0362f
Create Date: 2025-06-05 07:26:43.479511

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '8f3df49b6e4f'
down_revision = '31e468a0362f'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_tools', sa.Column('workspace_tool_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.drop_constraint('agent_tools_tool_id_fkey','agent_tools',type_='foreignkey')
    op.create_foreign_key('agent_tools_workspace_tool_id_fkey','agent_tools','workspace_tools',['workspace_tool_id'],['id'])
    op.drop_column('agent_tools', 'tool_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_tools', sa.Column('tool_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint('agent_tools_workspace_tool_id_fkey','agent_tools',type_='foreignkey')
    op.create_foreign_key('agent_tools_tool_id_fkey','agent_tools','tools',['tool_id'],['id'])
    op.drop_column('agent_tools', 'workspace_tool_id')
    # ### end Alembic commands ###
