"""empty message

Revision ID: a482c8ff849c
Revises: 1f7dc7cc3def
Create Date: 2025-02-03 09:12:05.226353

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'a482c8ff849c'
down_revision = '1f7dc7cc3def'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('source_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'source_id')
    # ### end Alembic commands ###
