"""empty message

Revision ID: 2e7236ad593b
Revises: f818b8b8aae9
Create Date: 2025-01-06 20:23:23.404510

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '2e7236ad593b'
down_revision = 'f818b8b8aae9'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_app_datasets', sa.Column('chatapp_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.drop_constraint('chat_app_datasets_chat_app_id_fkey', 'chat_app_datasets', type_='foreignkey')
    op.create_foreign_key(None, 'chat_app_datasets', 'chatapps', ['chatapp_id'], ['id'])
    op.drop_column('chat_app_datasets', 'chat_app_id')
    op.add_column('chat_app_generation_configs', sa.Column('chatapp_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.drop_constraint('chat_app_generation_configs_chat_app_id_fkey', 'chat_app_generation_configs', type_='foreignkey')
    op.create_foreign_key(None, 'chat_app_generation_configs', 'chatapps', ['chatapp_id'], ['id'])
    op.drop_column('chat_app_generation_configs', 'chat_app_id')
    op.add_column('chat_sessions', sa.Column('chatapp_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.drop_constraint('chat_sessions_chat_app_id_fkey', 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'chatapps', ['chatapp_id'], ['id'])
    op.drop_column('chat_sessions', 'chat_app_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('chat_app_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key('chat_sessions_chat_app_id_fkey', 'chat_sessions', 'chatapps', ['chat_app_id'], ['id'])
    op.drop_column('chat_sessions', 'chatapp_id')
    op.add_column('chat_app_generation_configs', sa.Column('chat_app_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat_app_generation_configs', type_='foreignkey')
    op.create_foreign_key('chat_app_generation_configs_chat_app_id_fkey', 'chat_app_generation_configs', 'chatapps', ['chat_app_id'], ['id'])
    op.drop_column('chat_app_generation_configs', 'chatapp_id')
    op.add_column('chat_app_datasets', sa.Column('chat_app_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_app_datasets', type_='foreignkey')
    op.create_foreign_key('chat_app_datasets_chat_app_id_fkey', 'chat_app_datasets', 'chatapps', ['chat_app_id'], ['id'])
    op.drop_column('chat_app_datasets', 'chatapp_id')
    # ### end Alembic commands ###
