"""empty message

Revision ID: 4d022997d6dc
Revises: f205bd2f321e
Create Date: 2025-04-24 04:10:57.535857

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '4d022997d6dc'
down_revision = 'f205bd2f321e'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('rows', sa.Integer(), nullable=True))
    op.add_column('files', sa.Column('columns', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'columns')
    op.drop_column('files', 'rows')
    # ### end Alembic commands ###
