"""empty message

Revision ID: f818b8b8aae9
Revises: 783e6c3310fe
Create Date: 2025-01-03 21:00:16.261711

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'f818b8b8aae9'
down_revision = '783e6c3310fe'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_app_generation_configs', 'chat_app_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('chat_sessions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('chat_sessions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('chat_sessions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'deleted_at')
    op.drop_column('chat_sessions', 'created_at')
    op.drop_column('chat_sessions', 'updated_at')
    op.alter_column('chat_app_generation_configs', 'chat_app_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
