"""empty message

Revision ID: 929d9dd320e5
Revises: 984d16a253e2
Create Date: 2025-06-27 11:18:58.453387

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '929d9dd320e5'
down_revision = '984d16a253e2'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_histories', sa.Column('pydantic_message', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_histories', 'pydantic_message')
    # ### end Alembic commands ###
