"""empty message

Revision ID: 4121fb6198a0
Revises: 4b10d3d5dcc8
Create Date: 2025-01-22 10:58:27.128864

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '4121fb6198a0'
down_revision = '4b10d3d5dcc8'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###

    # written manually
    op.execute("ALTER TYPE fileingestionstatustype ADD VALUE 'Exception'")
    op.execute("ALTER TYPE fileingestionstatustype RENAME TO fileingestionstatustype_old")
    op.execute("CREATE TYPE fileingestionstatustype AS ENUM ('Processing', 'Failed', 'Success', 'Not_Started', 'Exception')")
    op.execute("""ALTER TABLE file_ingestion 
                 ALTER COLUMN status TYPE fileingestionstatustype 
                 USING status::text::fileingestionstatustype""")
    op.execute("DROP TYPE fileingestionstatustype_old")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # written manually
    op.execute("ALTER TYPE fileingestionstatustype RENAME TO fileingestionstatustype_old")
    op.execute("CREATE TYPE fileingestionstatustype AS ENUM ('Processing', 'Failed', 'Success', 'Not_Started')")
    op.execute("""ALTER TABLE file_ingestion
                 ALTER COLUMN status TYPE fileingestionstatustype 
                 USING status::text::fileingestionstatustype""")
    op.execute("DROP TYPE fileingestionstatustype_old")
    # ### end Alembic commands ###
