"""empty message

Revision ID: e22028eb53f9
Revises: 4d022997d6dc
Create Date: 2025-05-13 09:57:46.048825

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import pgvector.sqlalchemy
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'e22028eb53f9'
down_revision = '4d022997d6dc'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'chunk_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
    op.create_index('ix_document_chunks_chunk_embedding_hnsw', 'document_chunks', ['chunk_embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'chunk_embedding': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 100})
    op.alter_column('documents', 'description_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'description_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               existing_nullable=True)
    op.drop_index('ix_document_chunks_chunk_embedding_hnsw', table_name='document_chunks', postgresql_using='hnsw', postgresql_ops={'chunk_embedding': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 100})
    op.alter_column('document_chunks', 'chunk_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               existing_nullable=True)
    # ### end Alembic commands ###
