"""empty message

Revision ID: db7db49a245a
Revises: 55fef71544c6
Create Date: 2025-07-07 06:10:48.408280

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db7db49a245a'
down_revision = '55fef71544c6'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mysql_sources', sa.Column('ssl_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('mysql_sources', sa.Column('ssl_ca_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('mysql_sources', sa.Column('ssl_cert_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('mysql_sources', sa.Column('ssl_key_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mysql_sources', 'ssl_key_path')
    op.drop_column('mysql_sources', 'ssl_cert_path')
    op.drop_column('mysql_sources', 'ssl_ca_path')
    op.drop_column('mysql_sources', 'ssl_mode')
