"""empty message

Revision ID: 681f909affd5
Revises: c78d3f1ca536
Create Date: 2025-07-10 04:12:05.780966

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '681f909affd5'
down_revision = 'c78d3f1ca536'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mysql_sources', 'ssl_key_path')
    op.drop_column('mysql_sources', 'ssl_cert_path')
    op.drop_column('mysql_sources', 'ssl_ca_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mysql_sources', sa.Column('ssl_ca_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mysql_sources', sa.Column('ssl_cert_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mysql_sources', sa.Column('ssl_key_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
