"""empty message

Revision ID: 8d12bfd5a570
Revises: e0e3bd08cc57
Create Date: 2025-07-21 09:58:15.765384

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d12bfd5a570'
down_revision = 'e0e3bd08cc57'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_histories', sa.Column('contexts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('chat_histories', 'context_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_histories', sa.Column('context_ids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=False))
    op.drop_column('chat_histories', 'contexts')
    # ### end Alembic commands ###
