"""empty message

Revision ID: 29a594d18eb1
Revises: e768ee5b2ef9
Create Date: 2025-08-26 05:50:35.281296

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '29a594d18eb1'
down_revision = '1a2b3c4d5e6f'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groove_sources',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key_vault_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auto_detection_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_monitored', sa.DateTime(), nullable=True),
    sa.Column('monitoring_frequency_minutes', sa.Integer(), nullable=True),
    sa.Column('last_ticket_number', sa.Integer(), nullable=True),
    sa.Column('ticket_batch_size', sa.Integer(), nullable=True),
    sa.Column('re_ingest_updated_tickets', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groove_sources_id'), 'groove_sources', ['id'], unique=False)
    op.create_index(op.f('ix_groove_sources_source_id'), 'groove_sources', ['source_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groove_sources_source_id'), table_name='groove_sources')
    op.drop_index(op.f('ix_groove_sources_id'), table_name='groove_sources')
    op.drop_table('groove_sources')
    # ### end Alembic commands ###
