"""empty message

Revision ID: 0d983303c03f
Revises: 4121fb6198a0
Create Date: 2025-01-23 13:31:57.909113

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '0d983303c03f'
down_revision = '4121fb6198a0'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_app_generation_configs', 'max_chunks_retrieved',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chat_app_generation_configs', 'max_tokens_to_sample',
               existing_type=sa.INTEGER(),
               nullable=True)

    # Add the column with a temporary default value
    op.add_column('chatapps', sa.Column('chat_app_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True, server_default='unstructured_chat_app'))
    # Update existing rows with a meaningful value (optional)
    op.execute("UPDATE chatapps SET chat_app_type = 'unstructured_chat_app'")
    # Remove the default value and make the column non-nullable
    op.alter_column('chatapps', 'chat_app_type', nullable=False, server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatapps', 'chat_app_type')
    op.alter_column('chat_app_generation_configs', 'max_tokens_to_sample',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chat_app_generation_configs', 'max_chunks_retrieved',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
