"""empty message

Revision ID: 227ab61e19f6
Revises: 5898cffd9184
Create Date: 2025-03-27 11:07:08.007171

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '227ab61e19f6'
down_revision = '5898cffd9184'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destination_pgvector', sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('destination_pgvector', 'table_name')
    # ### end Alembic commands ###
