"""empty message

Revision ID: b9f23c1754a2
Revises: a482c8ff849c
Create Date: 2025-02-25 22:05:47.879498

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel  # added


# revision identifiers, used by Alembic.
revision = "b9f23c1754a2"
down_revision = "a482c8ff849c"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chatapps",
        sa.Column(
            "voice_enabled", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.add_column(
        "chatapps",
        sa.Column(
            "graph_enabled", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chatapps", "graph_enabled")
    op.drop_column("chatapps", "voice_enabled")
    # ### end Alembic commands ###
