"""empty message

Revision ID: f0c73caca1af
Revises: 078d376d1ad3
Create Date: 2025-08-07 22:56:02.220927

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel  # added


# revision identifiers, used by Alembic.
revision = "f0c73caca1af"
down_revision = "cb58273122bc"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("ALTER TYPE chatmodelenum ADD VALUE IF NOT EXISTS 'GPT5'")
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
