"""empty message

Revision ID: e6669723540b
Revises: b9f23c1754a2
Create Date: 2025-02-27 16:46:26.397394

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel  # added


# revision identifiers, used by Alembic.
revision = "e6669723540b"
down_revision = "b9f23c1754a2"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "datasets",
        sa.Column("r2r_collection_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
    )
    op.add_column(
        "datasets",
        sa.Column(
            "knowledge_graph", sa.Boolean(), nullable=True, server_default=sa.false()
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("datasets", "knowledge_graph")
    op.drop_column("datasets", "r2r_collection_id")
    # ### end Alembic commands ###
