"""empty message

Revision ID: 5898cffd9184
Revises: f508fb884e52
Create Date: 2025-03-25 20:34:04.072478

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '5898cffd9184'
down_revision = 'f508fb884e52'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_embedding_token_counts',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('org_level_token_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_embedding_token_counts_id'), 'organization_embedding_token_counts', ['id'], unique=False)
    op.create_table('workspace_embedding_token_counts',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('org_token_count_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('workspace_level_token_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_token_count_id'], ['organization_embedding_token_counts.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_embedding_token_counts_id'), 'workspace_embedding_token_counts', ['id'], unique=False)
    op.create_table('dataset_embedding_token_counts',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('org_token_count_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('dataset_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('dataset_level_token_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['org_token_count_id'], ['organization_embedding_token_counts.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_embedding_token_counts_id'), 'dataset_embedding_token_counts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dataset_embedding_token_counts_id'), table_name='dataset_embedding_token_counts')
    op.drop_table('dataset_embedding_token_counts')
    op.drop_index(op.f('ix_workspace_embedding_token_counts_id'), table_name='workspace_embedding_token_counts')
    op.drop_table('workspace_embedding_token_counts')
    op.drop_index(op.f('ix_organization_embedding_token_counts_id'), table_name='organization_embedding_token_counts')
    op.drop_table('organization_embedding_token_counts')
    # ### end Alembic commands ###
