"""Add NOT_STARTED to GraphStatus enum

Revision ID: 15e572795ed8
Revises: 198adaa6b207
Create Date: 2025-08-22 06:46:31.597435

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel  # added


# revision identifiers, used by Alembic.
revision = "15e572795ed8"
down_revision = "198adaa6b207"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE graphstatus ADD VALUE IF NOT EXISTS 'NOT_STARTED'")
    # ### end Alembic commands ###


def downgrade():
    pass
