"""empty message

Revision ID: e1bf06f3cc65
Revises: 292c9ae74ae9
Create Date: 2025-03-14 21:19:00.276874

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel  # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e1bf06f3cc65"
down_revision = "292c9ae74ae9"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column("chat_histories", "context_ids")
    # op.add_column(
    #     "chat_histories",
    #     sa.Column("context_ids", postgresql.ARRAY(sa.UUID)),
    # )
    op.execute(
        "ALTER TABLE chat_histories ALTER COLUMN context_ids TYPE UUID[] USING string_to_array(context_ids, ',')::UUID[]"
    )

    op.alter_column(
        "chatapps",
        "voice_enabled",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "datasets",
        "knowledge_graph",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "datasets",
        "knowledge_graph",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "chatapps",
        "voice_enabled",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.execute(
        "ALTER TABLE chat_histories ALTER COLUMN context_ids TYPE VARCHAR USING array_to_string(context_ids, ',')"
    )
    # ### end Alembic commands ###
