"""empty message

Revision ID: d2e2399b0a95
Revises: 29a594d18eb1
Create Date: 2025-09-11 17:26:24.439929

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2e2399b0a95'
down_revision = '29a594d18eb1'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE system_tools 
        SET output_schema = 'app.tools.system_tools.schemas.plot_schema.PlotOutput',
            function_signature = 'async def generate_plotly_from_llm(request_data: PlotMockInput) -> PlotOutput'
        WHERE function_name = 'generate_plotly_from_llm'
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE system_tools 
        SET output_schema = 'app.tools.system_tools.schemas.plot_schema.PlotMockOutput',
            function_signature = 'async def generate_plotly_from_llm(request_data: PlotMockInput) -> PlotMockOutput'
        WHERE function_name = 'generate_plotly_from_llm'
    """)

    # ### end Alembic commands ###
