"""empty message

Revision ID: 984d16a253e2
Revises: a358e5a71fe1
Create Date: 2025-06-25 09:18:58.367345

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '984d16a253e2'
down_revision = 'a358e5a71fe1'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=True)
    # ### end Alembic commands ###
