"""empty message

Revision ID: 0fe2a9a9339a
Revises: f193aaae55f9
Create Date: 2025-03-18 20:54:21.932094

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '0fe2a9a9339a'
down_revision = 'f193aaae55f9'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('r2r_user', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('r2r_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'r2r_password')
    op.drop_column('organizations', 'r2r_user')
    # ### end Alembic commands ###
