"""empty message

Revision ID: f7715d8aad60
Revises: 0d983303c03f
Create Date: 2025-01-28 06:40:55.248232

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'f7715d8aad60'
down_revision = '0d983303c03f'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chatapps', 'chat_app_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chatapps', 'chat_app_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
