"""empty message

Revision ID: 31e468a0362f
Revises: b2352476eb92
Create Date: 2025-06-04 06:42:31.121526

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '31e468a0362f'
down_revision = 'b2352476eb92'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_tools', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace_tools', 'description')
    # ### end Alembic commands ###
