"""empty message

Revision ID: c6f62ce2526d
Revises: 681f909affd5
Create Date: 2025-07-10 23:34:42.413351

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c6f62ce2526d'
down_revision = '681f909affd5'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_clients',
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_clients_client_id'), 'api_clients', ['client_id'], unique=True)
    op.create_index(op.f('ix_api_clients_id'), 'api_clients', ['id'], unique=False)
    op.alter_column('agents', 'llm_model',
               existing_type=postgresql.ENUM('GPT35', 'GPT4o', 'GPT41', 'GPTo3', name='chatmodelenum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'llm_model',
               existing_type=postgresql.ENUM('GPT35', 'GPT4o', 'GPT41', 'GPTo3', name='chatmodelenum'),
               nullable=True)
    op.drop_index(op.f('ix_api_clients_id'), table_name='api_clients')
    op.drop_index(op.f('ix_api_clients_client_id'), table_name='api_clients')
    op.drop_table('api_clients')
    # ### end Alembic commands ###
