apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: amplifi
  name: rabbitmq-deployment
  namespace: amplifi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - envFrom:
          - secretRef:
              name: rabbitmq-secret
          image: rabbitmq:3-management
          name: rabbitmq-dev
          ports:
            - containerPort: 5672
              protocol: TCP
            - containerPort: 15672
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-data
      restartPolicy: Always
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-data
