apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: amplifi
  name: rabbitmq-data
  namespace: amplifi-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
